import type {PieceInGame} from "../Types";
import {getWordValidityGrids} from "./getWordValidityGrids";

describe("getWordValidityGrids", () => {
  test("returns two grids indicating whether the letter at that location is part of a valid word horizontally (grid 1) and vertically (grid 2)", () => {
    const pieces: PieceInGame[] = [
      {
        letters: [["R", "O", "N"]],
        id: 2,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 2,
        boardLeft: 2,
        boardTop: 3,
      },
      {
        letters: [["W", "S"]],
        id: 1,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 4,
        boardLeft: 4,
        boardTop: 1,
      },
      {
        letters: [["B"], ["L"], ["E"]],
        id: 4,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 4,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 4,
      },
      {
        letters: [["L", "I"]],
        id: 6,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 7,
        solutionLeft: 3,
        boardLeft: 3,
        boardTop: 7,
      },
      {
        letters: [
          ["C", "O"],
          ["", "R"],
          ["", "B"],
        ],
        id: 3,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 3,
      },
      {
        letters: [
          ["", "I", ""],
          ["S", "T", "S"],
        ],
        id: 5,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 6,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 6,
      },
      {
        letters: [
          ["B", "R", "O"],
          ["A", "", ""],
          ["B", "", ""],
        ],
        id: 0,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 1,
      },
    ];

    const expectedGrids = [
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, true, true, true, true, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, true, true, true, true, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, true, true, true, true, true, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
    ];

    expect(
      getWordValidityGrids({
        pieces,
        gridSize: 10,
        includeOriginalSolution: true,
      }),
    ).toEqual(expectedGrids);
  });

  test("if `includeOriginalSolution` is true, it returns the validity grid based on dictionary as well as the original solution encoded in the piece", () => {
    const pieces: PieceInGame[] = [
      {
        letters: [["R", "O", "N"]],
        id: 2,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 2,
        boardLeft: 2,
        boardTop: 3,
      },
      {
        letters: [["W", "A"]],
        id: 1,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 4,
        boardLeft: 4,
        boardTop: 1,
      },
      {
        letters: [["B"], ["L"], ["E"]],
        id: 4,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 4,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 4,
      },
      {
        letters: [["L", "I"]],
        id: 6,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 7,
        solutionLeft: 3,
        boardLeft: 3,
        boardTop: 7,
      },
      {
        letters: [
          ["C", "O"],
          ["", "R"],
          ["", "B"],
        ],
        id: 3,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 3,
      },
      {
        letters: [
          ["", "I", ""],
          ["S", "T", "S"],
        ],
        id: 5,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 6,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 6,
      },
      {
        letters: [
          ["B", "R", "O"],
          ["A", "", ""],
          ["B", "", ""],
        ],
        id: 0,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 1,
      },
    ];

    const expectedGrids = [
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, true, true, true, true, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, true, true, true, true, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, true, true, true, true, true, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
    ];

    expect(
      getWordValidityGrids({
        pieces,
        gridSize: 10,
        includeOriginalSolution: true,
      }),
    ).toEqual(expectedGrids);
  });

  test("if `includeOriginalSolution` is false, it returns the validity grid based on dictionary but not the original solution encoded in the piece", () => {
    const pieces: PieceInGame[] = [
      {
        letters: [["R", "O", "N"]],
        id: 2,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 2,
        boardLeft: 2,
        boardTop: 3,
      },
      {
        letters: [["W", "A"]],
        id: 1,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 4,
        boardLeft: 4,
        boardTop: 1,
      },
      {
        letters: [["B"], ["L"], ["E"]],
        id: 4,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 4,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 4,
      },
      {
        letters: [["L", "I"]],
        id: 6,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 7,
        solutionLeft: 3,
        boardLeft: 3,
        boardTop: 7,
      },
      {
        letters: [
          ["C", "O"],
          ["", "R"],
          ["", "B"],
        ],
        id: 3,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 3,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 3,
      },
      {
        letters: [
          ["", "I", ""],
          ["S", "T", "S"],
        ],
        id: 5,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 6,
        solutionLeft: 5,
        boardLeft: 5,
        boardTop: 6,
      },
      {
        letters: [
          ["B", "R", "O"],
          ["A", "", ""],
          ["B", "", ""],
        ],
        id: 0,
        poolIndex: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionTop: 1,
        solutionLeft: 1,
        boardLeft: 1,
        boardTop: 1,
      },
    ];

    const expectedGrids = [
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, true, true, true, true, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, true, true, true, true, true, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
      [
        [false, false, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, false, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, true, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false],
      ],
    ];

    expect(
      getWordValidityGrids({
        pieces,
        gridSize: 10,
        includeOriginalSolution: false,
      }),
    ).toEqual(expectedGrids);
  });

  test("an empty array of pieces results in all false", () => {
    const pieces: PieceInGame[] = [];
    expect(getWordValidityGrids({pieces, gridSize: 3})).toEqual([
      [
        [false, false, false],
        [false, false, false],
        [false, false, false],
      ],
      [
        [false, false, false],
        [false, false, false],
        [false, false, false],
      ],
    ]);
  });

  test("an error is thrown if either pieces or gridSize is undefined", () => {
    // @ts-expect-error intentionally testing invalid input
    expect(() => getWordValidityGrids({gridSize: 2})).toThrow(
      "Pieces must be defined.",
    );

    // @ts-expect-error intentionally testing invalid input
    expect(() => getWordValidityGrids({pieces: []})).toThrow(
      "Grid size must be defined.",
    );
  });

  test("if no pieces are on the board, the validity grids are all false", () => {
    const pieces: PieceInGame[] = [
      {
        letters: [
          ["", "C", ""],
          ["L", "A", "Y"],
          ["", "R", ""],
        ],
        id: 0,
        poolIndex: 1,
        boardTop: undefined,
        boardLeft: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionLeft: 0,
        solutionTop: 0,
      },
      {
        letters: [["K"], ["N"], ["O"]],
        id: 1,
        poolIndex: 1,
        boardTop: undefined,
        boardLeft: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionLeft: 0,
        solutionTop: 0,
      },
      {
        letters: [["N", "S"]],
        id: 2,
        poolIndex: undefined,
        boardTop: undefined,
        boardLeft: undefined,
        dragGroupTop: 1,
        dragGroupLeft: 1,
        solutionLeft: 0,
        solutionTop: 0,
      },
      {
        letters: [["E", "A"]],
        id: 3,
        poolIndex: undefined,
        boardTop: undefined,
        boardLeft: undefined,
        dragGroupTop: 1,
        dragGroupLeft: 1,
        solutionLeft: 0,
        solutionTop: 0,
      },
      {
        letters: [["B"], ["S"]],
        id: 4,
        poolIndex: 1,
        boardTop: undefined,
        boardLeft: undefined,
        dragGroupTop: undefined,
        dragGroupLeft: undefined,
        solutionLeft: 0,
        solutionTop: 0,
      },
    ];

    const expectedGrids = [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      ],
    ];
    expect(getWordValidityGrids({pieces, gridSize: 12})).toEqual(expectedGrids);
  });
});
